apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  csi:
    controllerExpandSecretRef:
      name: csi-cephfs-secret
      namespace: ceph-csi
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: ceph-csi
    volumeAttributes:
      clusterID: e74a9248-0bc3-11eb-937c-cb4abf66149d 
      fsName: cephfs
      mounter: kernel
      rootPath: //volumes/csi/test-subvolume/c4516214-85e1-4b6f-83c2-27bb05ead48c
      staticVolume: "true"
    volumeHandle: manual-pv2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-cephfs-sc-kernel
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pv2
  namespace: nv-apps
spec:
  storageClassName: csi-cephfs-sc-kernel
  volumeName: manual-pv2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
